[package]
name = "cirro-edge"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
instant-acme.workspace = true
rcgen.workspace = true
rustls.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio-rustls.workspace = true
tokio.workspace = true
tracing.workspace = true
x509-parser.workspace = true

[lints]
workspace = true
